### ISSUE TITLE
Compilation errors turn off beginners.

### ISSUE THREAD

**Issue by Ingo60** [Dierk/Real_World_Frege#4]
I suggest compiling and updating that stuff from time to time, especially when there have been changes in syntax and/or libraries.

For an example why this would be a good idea, see http://stackoverflow.com/questions/33946464/problems-with-code-in-the-frege-repl

**Comment by Dierk** [comment]
updated with commit 4990299eeaa6358751eb780bec3ddb125565a413

Well, it is only a compile error if you compile it elsewhere (repl) not using the provided gradle build automation that refers to the frege version that the code is known to work with.
